module.exports = {
  apps: [
    {
      name: 'nerv-dashboard',
      cwd: 'C:/Users/Rohan/aeon/dashboard',
      script: 'node_modules/next/dist/bin/next',
      args: 'dev -p 5555',
      interpreter: 'C:/Program Files/nodejs/node.exe',
      env: {
        NODE_ENV: 'development',
        PORT: '5555',
        AEON_REPO_ROOT: 'C:/Users/Rohan/aeon',
        AEON_REPO: 'bludragon66613-sys/NERV_02',
        DASHBOARD_SECRET: process.env.DASHBOARD_SECRET,
        GITHUB_TOKEN: process.env.GITHUB_TOKEN || '',
        CLAUDE_MEM_URL: 'http://localhost:37777',
        OPENCLAW_PROXY_URL: 'http://localhost:5557',
        OPENCLAW_PROXY_SECRET: process.env.OPENCLAW_PROXY_SECRET,
        OPENCLAW_WS_URL: 'ws://127.0.0.1:18789',
        AEON_WORKFLOW_FILE: 'aeon.yml',
        AEON_REGISTRY_PATH: 'C:/Users/Rohan/aeon/dashboard/.cache/command-registry.json',
        JWT_TTL_SECONDS: '86400',
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      pre_start: 'node -e "try{require(\'fs\').rmSync(\'C:/Users/Rohan/aeon/dashboard/.next/dev/lock\')}catch(e){}"',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'openclaw-proxy',
      cwd: 'C:/Users/Rohan/aeon/dashboard/openclaw-proxy',
      script: 'index.js',
      interpreter: 'C:/Program Files/nodejs/node.exe',
      env: {
        NODE_ENV: 'production',
        PORT: '5557',
        OPENCLAW_URL: 'http://127.0.0.1:18789',
        OPENCLAW_HOOKS_TOKEN: process.env.OPENCLAW_HOOKS_TOKEN || '',
        OPENCLAW_PROXY_SECRET: process.env.OPENCLAW_PROXY_SECRET,
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
